import ConfigureAmplifyClientSide from "@/components/ConfigureAmplifyClientSide";
import "./globals.css";
import { Amplify } from "aws-amplify";
import { config } from '@/utils/awsConfig';
import { ThemeProvider } from "@/themes/theme-provider";

console.log("🚀 ~ layout config:", config);

//server side configuration
Amplify.configure({ ...config }, { ssr: true });

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Trustie Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConfigureAmplifyClientSide />
          <main className="bg-background min-h-screen h-full">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
